# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            OfBrooklyn.com
tagline:          "Samuel Clay's collected writings"
description:      ""

url:              http://www.ofbrooklyn.com
baseurl:          /

author:
  name:           'Samuel Clay'
  url:            https://www.samuelclay.com

paginate:         5
excerpt_separator: <!--more-->

markdown:    kramdown
highlighter: pygments

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samuelclay/ofbrooklyn/

gems:
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb
  