
# Setup
title:            OfBrooklyn.com
tagline:          "Samuel Clay's collected writings"
description:      ""

url:              https://www.ofbrooklyn.com
permalink:        :year/:month/:i_day/:title/
timezone:         UTC

author:
  name:           'Samuel Clay'
  url:            https://www.samuelclay.com

paginate:         5
excerpt_separator: <!--more-->

feed:
  path:           feeds/all.html

markdown:         kramdown
highlighter:      rouge

version:          2.1.0

github:
  repo:           https://github.com/samuelclay/ofbrooklyn/
  
plugins:
  - jekyll-paginate
  - jekyll-gist
  - rouge
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
  